orbs:
  godel:
    jobs:
      verify:
        description: Runs godelw verification
        docker:
          - image: nmiyake/go:go-darwin-linux-no-cgo-1.10.3-t130
            environment:
              CGO_ENABLED: 0
        working_directory: /go/src/github.com/palantir/distgo
        steps:
          - run: echo "hello"

version: 2.1

#jobs:
#  verify:
#    docker:
#      - image: nmiyake/go:go-darwin-linux-no-cgo-1.10.3-t130
#        environment:
#          CGO_ENABLED: 0
#    working_directory: /go/src/github.com/palantir/distgo
#    steps:
#      - run: echo "hello"

workflows:
  version: 2
  build-publish:
    jobs:
      - godel/verify:
          name: "verify"
